# Generated by Django 5.2.9 on 2025-12-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('SEASONAL', 'Seasonal'), ('BULK', 'Bulk'), ('USER_TIER', 'User Tier')], max_length=20)),
                ('priority', models.IntegerField()),
                ('config', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
